[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：支持港/日/美

ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/CFnat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/BanProgramAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/adobe.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/IDM.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Xbox.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Apple.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Telegram.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/OpenAi.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/ai.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Copilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/GithubCopilot.list
ruleset=🤖 OpenAi,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Claude.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Netflix.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/Emby.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/ProxyLite.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/CMBlog.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/mi0e/ACL4SSR/main/rules/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=☑️ 手动切换`select`.*`[]🚑 故障转移`[]♻️ 自动选择`[]🇭🇰 香港`[]🇯🇵 日本`[]🇺🇸 美国
custom_proxy_group=🚀 节点选择`select`[]☑️ 手动切换`[]🇭🇰 香港`[]🇯🇵 日本`[]🇺🇸 美国`DIRECT
custom_proxy_group=🚑 故障转移`fallback`[]🇭🇰 香港`[]🇺🇸 美国`[]🇯🇵 日本`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`.*`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]DIRECT`(NF|奈飞|解锁|Netflix|NETFLIX|Media|MITM)
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🤖 OpenAi`select`[]🚀 节点选择`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=🇭🇰 香港`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国`url-test`(美|San Jose|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`http://cp.cloudflare.com/generate_204`300,,150

enable_rule_generator=true
overwrite_original_rules=true

port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false
find-process-mode: strict
external-controller: '127.0.0.1:9090'
profile:
  store-selected: true
  store-fake-ip: true
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
ntp:
  enable: true
  write-to-system: false
  server: ntp.aliyun.com
  port: 123
  interval: 30
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
dns:
  enable: true
  listen: ':53'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  prefer-h3: false
  respect-rules: true
  use-hosts: false
  use-system-hosts: false
  ipv6: true
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - +.market.xiaomi.com
    - localhost.ptlogin2.qq.com
    - '*.msftncsi.com'
    - www.msftconnecttest.com
  default-nameserver:
    - system
    - 223.6.6.6
    - 8.8.8.8
    - '2400:3200::1'
    - '2001:4860:4860::8888'
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - 8.8.8.8
  direct-nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver-follow-policy: true
  fallback:
    - 'https://1.1.1.1/dns-query'
    - 'https://8.8.8.8/dns-query'
    - 'https://dns.google/dns-query'
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.twitter.com
      - +.github.com
  proxy-server-nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - 'tls://223.5.5.5'
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  dns-hijack:
    - 'any:53'
  device: SakuraiTunnel
  mtu: 1500
  endpoint-independent-nat: true
